pytest-dev/execnet

- doc/conf.py
Sphinx 1.7 deprecated the use of a single string in `html_sidebars`, and Sphinx 2.0 has dropped support for this altogether.
> doc: use a list for html_sidebars

- testing/conftest.py
The later is obsolete with pytest5+
> Use fixturenames instead of funcargnames

- testing/test_gateway.py
- testing/test_xspec.py
While working on reproducible builds for openSUSE, I noticed
that test_popen_nice would randomly fail on 1-core-VMs
```
remotenice = gw.remote_exec(getnice).receive()
gw.exit()
if remotenice is not None:
gw = makegateway("popen//nice=5")
remotenice2 = gw.remote_exec(getnice).receive()
>           assert remotenice2 == remotenice + 5
E           assert 0 == (0 + 5)
```
> Fix random test failure

- testing/test_gateway.py
As of Pytest 5.1.0
> pytest.raises and pytest.warns no longer support strings as the
> second argument
https://docs.pytest.org/en/latest/changelog.html#removals
Fixes: https://github.com/pytest-dev/execnet/issues/106
> Fixed testing against Pytest 5.1

- CHANGELOG.rst
- execnet/gateway.py
- execnet/gateway_base.py
- testing/test_gateway.py
This removes the if/else case when the file_name is not present, and
relies once again on linecache, fixing a problem where `source` would
always be set to `None` in remote modules
Fixes issue #108
> re-introduce linecache usage again

- CHANGELOG.rst
- doc/basics.rst
- doc/example/test_debug.rst
- doc/example/test_proxy.rst
- execnet/gateway_base.py
- execnet/gateway_bootstrap.py
- testing/test_basics.py
- testing/test_gateway.py
- testing/test_multi.py
- testing/test_termination.py
See https://github.com/pytest-dev/pytest/issues/7344.
This is *mostly* internal, with the possible exception of renaming `SlaveGateway` to `WorkerGateway`... I'm going for the optimistic change first though, it's easy to roll back to a partial fix if we need to.
> Replace "slave" terminology

- CHANGELOG.rst
- execnet/gateway.py
should improve https://github.com/pytest-dev/pytest-xdist/issues/620
> waitclose in _rinfo() call

- execnet/gateway_base.py
The new is_set() snake-case spelling has been available since
Python 2.6:
https://docs.python.org/2/library/threading.html#threading.Event.is_set
The old isSet() camel-case spelling raises a deprecation warning with
Python 3.10:
https://docs.python.org/3.10/whatsnew/3.10.html#deprecated
(almost at the end)
> Update threading.Event.isSet() calls

- CHANGELOG.rst
- execnet/__init__.py
- execnet/gateway.py
- execnet/gateway_bootstrap.py
- execnet/multi.py
- setup.py
The advantages of apipkg AFAIU are:
- Nicer syntax. Doesn't seem very important.
- Enable lazy-loading of the sub-modules, allowing for a faster startup
and not paying the import cost at all if not used. However execnet is
not that big (~2000 lines) and most users will end up importing the
big file (gateway_base.py) anyway.
- Allows absolute imports in sub-modules without worrying about
"cannot import from partially-initialized module" errors. Doesn't seem
very important.
So it does not seem worthwhile imposing this dependency on all users of
execnet/pytest-xdist just for that.
> Stop using apipkg

- testing/conftest.py
- testing/test_channel.py
- testing/test_gateway.py
- testing/test_multi.py
- testing/test_rsync.py
- testing/test_serializer.py
- testing/test_termination.py
- testing/test_threadpool.py
- tox.ini
This adds an explicit dependency to `py`, and also fixes some low hanging fruits replacing `py.test` by `pytest`.
Also fixes #158.
> Fix CI for pytest 7.2+

- tox.ini
... to get better support for `tox-current-env`.
> tox should call pytest indirectly

- execnet/rsync_remote.py
- testing/test_rsync.py
When the source directories hierarchy is read-only, the read-only mode
would be preserved at the destination, preventing the directories to
be recreated by a normal user (a permission denied error, EACCES would
be raised).
* execnet/rsync_remote.py (serve_rsync.receive_directory_structure):
Bitwise OR to ensure the write bit is set on received directories.
> rsync_remote: Fix a problem when receiving a read-only directories.

- .github/workflows/main.yml
Running on every push is redundant and somewhat annoying in forks.
> ci: don't run on every push

- CHANGELOG.rst
- doc/example/conftest.py
- doc/example/svn-sync-repo.py
- doc/example/sysinfo.py
- execnet/gateway.py
- execnet/rsync.py
- testing/conftest.py
- testing/test_basics.py
- testing/test_channel.py
- testing/test_gateway.py
- testing/test_multi.py
- testing/test_rsync.py
- testing/test_serializer.py
- testing/test_termination.py
- testing/test_threadpool.py
- testing/test_xspec.py
- tox.ini
Mostly removing use of `py` and `testdir` - see commits.
> testing: some cleanups

- execnet/gateway_base.py
- execnet/gateway_io.py
- execnet/gateway_socket.py
- execnet/multi.py
- execnet/script/shell.py
- execnet/script/socketserver.py
- execnet/script/socketserverservice.py
- execnet/script/xx.py
These are some small internal refactoring commits in preparation for adding type annotations. The bigger changes are rewriting some clever hpk42-style code that unfortunately can't be statically analyzed (I have a pending change to also improve ExecModel in this regard).
> Typing prep

- CHANGELOG.rst
- execnet/gateway_base.py
- tox.ini
> Specify encoding in fdopen.

- execnet/gateway_bootstrap.py
It's safe to assume that this is always utf-8-safe because we only ever use the function to send Python source code, which must be utf-8 encodable (and indeed utf-8 at rest).  Importantly, it's _not_ relevant that the filesystem might use a non-utf8 encoding, because this directory name has already been decoded to a string and will be re-encoded from the string literal in the utf-8 source code to whatever the filesystem encoding happens to be at the other end.
Does not include tests because they'd be very painful to write, it's correct by inspection (grep `sendexec(`), and can't possibly break anything that already worked.
Fixes #153, unblocks #199.
> Use utf-8 so we support non-ascii module names

- README.rst
Seems this was removed by accident in https://github.com/pytest-dev/execnet/commit/e4d606f97e59d1704475652333334c327210dbbe#diff-7b3ed02bc73dc06b7db906cf97aa91dec2b2eb21f2d92bc5caa761df5bbc168f.
> Bring back notice about maintenance only

- .pre-commit-config.yaml
- pyproject.toml
- src/execnet/gateway_base.py
- src/execnet/gateway_io.py
- src/execnet/rsync_remote.py
- src/execnet/script/shell.py
- testing/test_threadpool.py
Unfortunately black and reorder-python-imports are no longer compatible between each other:
https://github.com/asottile/reorder-python-imports/issues/367
https://github.com/asottile/reorder-python-imports/issues/366
https://github.com/psf/black/issues/4175
Take this opportunity to try out ruff.
Closes #231.
> Use ruff in place of black and reorder-python-imports

- pyproject.toml
- src/execnet/__init__.py
- src/execnet/gateway.py
- src/execnet/gateway_base.py
- src/execnet/gateway_io.py
- src/execnet/multi.py
- src/execnet/rsync_remote.py
- src/execnet/script/quitserver.py
- src/execnet/script/socketserverservice.py
- testing/conftest.py
- testing/test_basics.py
- testing/test_channel.py
- testing/test_serializer.py
As brought up in https://github.com/pytest-dev/execnet/pull/239#issuecomment-1917570146, the isort settings for ruff were not being applied.
> Fix ruff isort configuration

- .github/workflows/test.yml
- .pre-commit-config.yaml
- CHANGELOG.rst
- doc/install.rst
- pyproject.toml
- testing/conftest.py
- tox.ini
> Remove support for Python 3.7, add official support for Python 3.12

- src/execnet/gateway.py
- src/execnet/gateway_base.py
- src/execnet/gateway_socket.py
- src/execnet/multi.py
- src/execnet/script/socketserver.py
- testing/test_basics.py
In Python 3 it's better to handle exception objects directly, they now carry their traceback.
> Avoid using sys.exc_info

- testing/test_xspec.py
`SshGateway` no longer exists.
> testing: fix broken test

- testing/test_termination.py
testdir is using the legacy py.path.
> testing: switch testdir -> pytester

- .pre-commit-config.yaml
- pyproject.toml
- src/execnet/gateway.py
- src/execnet/gateway_base.py
- src/execnet/gateway_bootstrap.py
- src/execnet/rsync.py
- src/execnet/rsync_remote.py
- src/execnet/script/shell.py
- src/execnet/script/socketserver.py
- testing/conftest.py
- testing/test_basics.py
- testing/test_gateway.py
- testing/test_serializer.py
- testing/test_termination.py
- testing/test_threadpool.py
- testing/test_xspec.py
Rules list adapted from pytest's configuration.
> Enable more lints

- .pre-commit-config.yaml
- doc/example/redirect_remote_output.py
- doc/example/sysinfo.py
- pyproject.toml
- src/execnet/gateway.py
- src/execnet/gateway_base.py
- src/execnet/gateway_bootstrap.py
- src/execnet/gateway_io.py
- src/execnet/gateway_socket.py
- src/execnet/multi.py
- src/execnet/rsync.py
- src/execnet/rsync_remote.py
- src/execnet/script/shell.py
- src/execnet/script/socketserver.py
- src/execnet/script/socketserverservice.py
- src/execnet/xspec.py
- testing/conftest.py
- testing/test_basics.py
- testing/test_channel.py
- testing/test_compatibility_regressions.py
- testing/test_gateway.py
- testing/test_multi.py
- testing/test_rsync.py
- testing/test_serializer.py
- testing/test_termination.py
- testing/test_threadpool.py
- testing/test_xspec.py
The typing is still not optimal and not ready to be exposed, but can serve as an initial basis.
> Add initial typing

- CHANGELOG.rst
- src/execnet/__init__.py
- src/execnet/gateway_base.py
- src/execnet/multi.py
A couple of changes from using execnet's typing in pytest-xdist.
> Couple of typing fixes

- CHANGELOG.rst
- src/execnet/gateway_base.py
- testing/test_serializer.py
Accidental regression in 2.1.0 (c58d485ff97d401dd02516cce).
Fix #267.
Thanks to @RonnyPfannschmidt for tracking down the buggy line.
> gateway_base: fix `load(strconfig)` getting ignored

- .github/chronographer.yml
This app allows requiring changelog fragments to be included with each pull request.
A new `skip news` label is expected to be created in the repo to match the configuration.
> 💅 Add a config for the Chronographer GitHub App

- .github/patchback.yml
This patch prepares the project's backporting process to start being handled by the Patchback GitHub App [[1]].
It is expected that a new label like `backport 2.1.x` is created to match the configuration.
[1]: https://github.com/apps/patchback
> 💅 Add a config for the Patchback GitHub App
